controller_list:
  - name: fake_manipulator_controller
    type: $(arg execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_end_effector_controller
    type: $(arg execution_type)
    joints:
      - robotiq_85_left_knuckle_joint
      - robotiq_85_left_finger_joint
      - robotiq_85_right_finger_joint
initial:  # Define initial robot poses.
  - group: manipulator
    pose: home
  - group: end_effector
    pose: ee_open